name: pihnn-env

channels:
  - anaconda
  - conda-forge

dependencies:
  - pip
  - conda-build
  - conda-verify
  - sphinx
  - pydata-sphinx-theme
  - sphinx-autoapi
  - sphinxcontrib-youtube
  - tqdm
  - matplotlib>=3.5.0
  - numpy>=1.22.0
  - pytorch>=1.11.0
  - scipy>=1.9.0