name: pihnn-devo-env

channels:
  - anaconda
  - conda-forge

dependencies:
  - python>=3.10
  - matplotlib>=3.5.0
  - numpy>=1.22.0
  - scipy>=1.9.0
  - tqdm
  - pip
  - pip:
      - torch
      - torchvision
      - git+https://github.com/teocala/pihnn.git